services:
  dm-web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'
      SQLCONNSTR_DownloadManagerDb: Server=127.0.1.1,1433;Database=DownloadManagerDb;User Id=sa;Password=Passw0rd; # hostname -I