services:
  dm-web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    networks:
      - "my_transparent_network"
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'
      SQLCONNSTR_DownloadManagerDb: Server=172.24.114.199,1433;Database=DownloadManagerDb;User Id=sa;Password=Passw0rd; # hostname -I