services:
  dm-db:
    container_name: dm-db
    hostname: dm-db
    build: .
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Passw0rd'
      MSSQL_PID: 'Developer' 
      MSSQL_TCP_PORT: 1433