name: Deploy code

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        options: 
          - DEV
          - DEV-2

jobs:
  build-and-deploy:
    runs-on: windows-latest  
    environment: ${{github.event.inputs.environment}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet packages
      run: nuget restore DownloadManager.sln  

    - name: Build solution
      run: msbuild /p:Configuration=Release DownloadManager.sln

    - name: Deploy DACPAC to Azure SQL Database
      uses: Azure/sql-action@v2.3
      with:
        connection-string: Server=tcp:${{vars.AZURE_SQL_SERVER_NAME}}.database.windows.net,1433;Initial Catalog=${{vars.AZURE_SQL_DATABASE_NAME}};Persist Security Info=False;User ID=${{vars.SQL_ADMIN_LOGIN}};Password=${{secrets.SQL_ADMIN_PASSWORD}};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=60;
        path: ./DownloadManager.Data.Database/bin/Release/DownloadManager.Data.Database.dacpac
        build-arguments: '/p:DropObjectsNotInSource=True /p:BlockOnPossibleDataLoss=False'
        action: Publish
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'  

    - name: Install dependencies (Angular)
      working-directory: ./DownloadManager.Web/ClientApp  
      run: npm install

    - name: Build Angular
      working-directory: ./DownloadManager.Web/ClientApp 
      run: npm run build -- --configuration=production
      
    - name: Publish API
      run: msbuild /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:Configuration=Release DownloadManager.Web/DownloadManager.Web.csproj

    - name: Archive Build Files
      uses: vimtor/action-zip@v1.1
      with:
        dest: 'WebApp.zip'
        files: 'DownloadManager.Web\ClientApp\dist\client-app\'

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        auth-type: SERVICE_PRINCIPAL

    - name: Deploy to Azure Web App
      run: |
        az webapp deploy --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --name ${{ vars.AZURE_WEBAPP_NAME }} --src-path "WebApp.zip"
