name: Deploy code (ms-dm-dev-app & ms-dm-dev-sqldb)

on:
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Choose the build configuration'
        required: true
        default: 'Release'
        type: choice
        options:
          - Release
          - Debug

jobs:
  build-and-deploy:
    runs-on: windows-latest  
    environment: DEV

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet packages
      run: nuget restore DownloadManager.sln  

    - name: Build solution
      run: msbuild /p:Configuration=${{ github.event.inputs.configuration }} DownloadManager.sln

    - name: Publish API
      run: msbuild /t:Publish /p:Configuration=${{ github.event.inputs.configuration }} /p:PublishDir="DownloadManager.Web/publish" ./DownloadManager.Web.csproj

    - name: Deploy DACPAC to Azure SQL Database
      uses: Azure/sql-action@v2.3
      with:
        connection-string: Server=tcp:${{vars.AZURE_SQL_SERVER_NAME}}.database.windows.net,1433;Initial Catalog=${{vars.AZURE_SQL_DATABASE_NAME}};Persist Security Info=False;User ID=${{vars.SQL_ADMIN_LOGIN}};Password=${{secrets.SQL_ADMIN_PASSWORD}};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=60;
        path: ./DownloadManager.Data.Database/bin/${{ github.event.inputs.configuration }}/DownloadManager.Data.Database.dacpac
        build-arguments: '/p:DropObjectsNotInSource=True /p:BlockOnPossibleDataLoss=False'
        action: Publish
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'  

    - name: Install dependencies (Angular)
      working-directory: ./DownloadManager.Web/ClientApp  
      run: npm install

    - name: Build Angular
      working-directory: ./DownloadManager.Web/ClientApp 
      run: npm run build -- --configuration=production

    - name: Archive Backend Build Files
      uses: vimtor/action-zip@v1.1
      with:
        dest: 'WebAppBackend.zip'
        files: 'DownloadManager.Web\publish\'

    - name: Archive Frontend Build Files
      uses: vimtor/action-zip@v1.1
      with:
        dest: 'WebAppFrontend.zip'
        files: 'DownloadManager.Web\ClientApp\dist\client-app\'

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        auth-type: SERVICE_PRINCIPAL

    - name: Deploy API to Azure Web App
      run: |
        az webapp deploy --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --name ${{ vars.AZURE_WEBAPP_NAME }} --src-path "WebAppBackend.zip"

    - name: Deploy Angular app to Azure Web App
      run: |
        az webapp deploy --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --name ${{ vars.AZURE_WEBAPP_NAME }} --src-path "WebAppFrontend.zip"
