name: Create resources (ms-dm-dev-rg)

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: DEV

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          auth-type: SERVICE_PRINCIPAL
      - name: ARM Deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ vars.AZURE_RESOURCE_GROUP }}
          template: ./DownloadManager.ArmTemplate/azuredeploy.json
          parameters: |
            ./DownloadManager.ArmTemplate/azuredeploy.parameters.json
            sqlAdministratorLogin=${{ vars.SQL_ADMIN_LOGIN }}
            sqlAdministratorPassword=${{ secrets.SQL_ADMIN_PASSWORD }}
